language: python
matrix:
    include:
        - python: "3.6"
          env: TEST_SUITE=suite_3_6 TOX_ENV=py36
        - python: "3.6"
          env: TEST_SUITE=suite_3_6 TOX_ENV=pep8

sudo: required
before_install:
  - sudo apt-get install build-essential python-dev

install: pip install tox setuptools virtualenv coveralls --upgrade

script: tox -v -e $TOX_ENV -- -v

after_success: coveralls

notifications:
  email:
    - bm_witness@yahoo.com

